name: Rename Draft Articles

on:
  schedule:
    - cron: '0 9 * * *'

  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  check_draft_articles:
    runs-on: ubuntu-latest
    outputs:
      publish_required: ${{ steps.check_articles_to_publish.outputs.PUBLISH_ARTICLES }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: PowerShell Module Cache
      uses: potatoqualitee/psmodulecache@v5.2
      with:
        modules-to-cache: powershell-yaml

    - name: Rename Draft Articles
      id: rename_drafts
      run: |
        Set-Location -Path $env:GITHUB_WORKSPACE
        .github/scripts/RenameDraftArticles.ps1

    - name: Check for New Articles to Publish
      id: check_articles_to_publish
      run: |
        if ([System.Convert]::ToBoolean($env:DRAFTS_ARTICLES_RENAMED)) {
          'Found and renamed at least one draft article requiring the site to be published.'
          'PUBLISH_ARTICLES=true' >> $env:GITHUB_OUTPUT
        } else {
          'No articles matched the criteria to be renamed and published.'
          'PUBLISH_ARTICLES=false' >> $env:GITHUB_OUTPUT
        }

    - name: Import GPG
      uses: crazy-max/ghaction-import-gpg@v5.2.0
      if: ${{ steps.check_articles_to_publish.outputs.PUBLISH_ARTICLES }}
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.2.4
      if: ${{ steps.check_articles_to_publish.outputs.PUBLISH_ARTICLES }}
      with:
        commit-message: publish draft article
        committer: ${{ vars.GIT_USER_NAME }} <${{ vars.GIT_USER_EMAIL }}>
        branch: draft-articles
        title: Create Pull Request
        body: Create pull request to publish renamed article
        delete-branch: true

    - name: Find Pull Request
      uses: juliangruber/find-pull-request-action@v1.8.0
      if: ${{ steps.check_articles_to_publish.outputs.PUBLISH_ARTICLES }}
      id: find-pull-request
      with:
        branch: draft-articles

    - name: Merge Pull Request
      id: merge-pull-request
      uses: juliangruber/merge-pull-request-action@v1.1.0
      if: ${{ steps.check_articles_to_publish.outputs.PUBLISH_ARTICLES }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.find-pull-request.outputs.number }}
        method: merge

